version: "3.8"

services:
  postgres:
    image: postgres:15-alpine
    container_name: team-tracker-db
    environment:
      POSTGRES_DB: team_tracker
      POSTGRES_USER: teamtracker
      POSTGRES_PASSWORD: teamtracker123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./server/db/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - team-tracker-network

  server:
    image: node:18-alpine
    container_name: team-tracker-server
    environment:
      NODE_ENV: development
      DB_HOST: postgres
      DB_PORT: 5432
      DB_NAME: team_tracker
      DB_USER: teamtracker
      DB_PASSWORD: teamtracker123
      JWT_SECRET: your-super-secret-jwt-key-change-in-production
      PORT: 3030
    working_dir: /app
    command: npm run dev
    ports:
      - "3030:3030"
    depends_on:
      - postgres
    volumes:
      - ./server:/app
    networks:
      - team-tracker-network

  client:
    image: node:18-alpine
    container_name: team-tracker-client
    environment:
      REACT_APP_API_URL: http://localhost:3030/api
      NODE_ENV: development
    working_dir: /app
    command: npm run start
    ports:
      - "3000:3000"
    depends_on:
      - server
    volumes:
      - ./client:/app
    networks:
      - team-tracker-network

  mock-workday:
    build:
      context: ./mock-workday
      dockerfile: Dockerfile
    container_name: mock-workday
    ports:
      - "4000:4000"
    networks:
      - team-tracker-network

volumes:
  postgres_data:

networks:
  team-tracker-network:
    driver: bridge
